package main

import (
	"context"
	"log/slog"
	"os"
	"os/signal"
	"syscall"

	"go-api-kbt/internal/app"
	"go-api-kbt/internal/config"
	"go-api-kbt/internal/observability"
	"go-api-kbt/pkg/logger"

	_ "go-api-kbt/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title KBT API
// @version 1.0
// @description This is the API for Kedunglo Biking Team.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1
// @schemes http

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

func main() {
	logger := logger.NewLogger(os.Stdout, slog.LevelInfo)

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	cfg, err := config.Load(logger)
	if err != nil {
		logger.Error("failed to load config", slog.String("error", err.Error()))
		os.Exit(1)
	}

	provider, err := observability.Setup(ctx, cfg, logger)
	if err != nil {
		logger.Error("failed to setup observability", slog.String("error", err.Error()))
		os.Exit(1)
	}
	defer func() {
		if err := provider.Shutdown(context.Background()); err != nil {
			logger.Error("failed to shutdown telemetry", slog.String("error", err.Error()))
		}
	}()

	application, err := app.New(ctx, cfg, logger)
	if err != nil {
		logger.Error("failed to create app", slog.String("error", err.Error()))
		os.Exit(1)
	}

	go func() {
		<-ctx.Done()
		logger.Info("shutting down application")
		if err := application.Shutdown(context.Background()); err != nil {
			logger.Error("graceful shutdown failed", slog.String("error", err.Error()))
		}
	}()

	if err := application.Start(); err != nil {
		logger.Error("application stopped", slog.String("error", err.Error()))
	}
}
